### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by sinamiandashti** [vgarvardt/ZfSimpleMigrations#1]
can u please let us know how to use this module?

where shoud i use that cli command : migration

should i add this module to module list ?

**Comment by fabiopaiva** [comment]
How to down?

i tried

    php public/index.php migration apply 20150610162318 --down

don't work

**Comment by fabiopaiva** [comment]
this way works: 

    php public/index.php migration apply default 20150610162318 --down --force
