### ISSUE TITLE
migration command?

### ISSUE THREAD

**Issue by mxmz-** [vgarvardt/ZfSimpleMigrations#10]
How come this is even working, where there is no bash script or anything, that enables migration command to even work?

**Comment by vgarvardt** [comment]
Please read README installation and usage instructions - module works from common front controller

**Comment by mxmz-** [comment]
I did read it, and your documentation is lacking as it does not say the stuff that you mentioned now. First instinct is that you run it from a command line, but there is no command for migration.

**Comment by vgarvardt** [comment]
> First instinct is that you run it from a command line, but there is no command for migration

`php public/index.php ...`

**Comment by mxmz-** [comment]
Why that can not be specified in readme?

**Comment by vgarvardt** [comment]
It's a common way of running any commands in ZF2. README describes only module-specific functionality.
