### ISSUE TITLE
Using outside of ZF2 Application

### ISSUE THREAD

**Issue by jcrawford** [vgarvardt/ZfSimpleMigrations#11]
I have a library I have created using components from the ZF2 library while not using a skeleton web application.  I have an entry point which uses classes which depend on ZF2 components like Zend\Http\Client, etc so i am not using the application configs or modules.  I was wondering if there was a way to use your module without actually being a module in an application.

**Comment by vgarvardt** [comment]
Look at MigrateControllerFactory - all "magic" happens here. You can try to use your own factory to instantiate controller.
